export default [
  {
    name: 'Georgia',
    code: '7840',
    capital: 'Abkhazia',
    iso2: 'GE',
  },
  {
    name: 'Georgia',
    code: '7940',
    capital: 'Abkhazia',
    iso2: 'GE',
  },
  {
    name: 'Afghanistan',
    code: '93',
    capital: 'Kabul',
    iso2: 'AF',
  },
  {
    name: 'Åland Islands',
    code: '35818',
    capital: 'Mariehamn',
    iso2: 'AX',
  },
  {
    name: 'Albania',
    code: '355',
    capital: 'Tirana',
    iso2: 'AL',
  },
  {
    name: 'Algeria',
    code: '213',
    capital: 'Algiers',
    iso2: 'DZ',
  },
  {
    name: 'American Samoa',
    code: '1684',
    capital: 'Pago Pago',
    iso2: 'AS',
  },
  {
    name: 'Andorra',
    code: '376',
    capital: 'Andorra la Vella',
    iso2: 'AD',
  },
  {
    name: 'Angola',
    code: '244',
    capital: 'Luanda',
    iso2: 'AO',
  },
  {
    name: 'Anguilla',
    code: '1264',
    capital: 'The Valley',
    iso2: 'AI',
  },
  {
    name: 'Antigua and Barbuda',
    code: '1268',
    capital: 'St. John\'s',
    iso2: 'AG',
  },
  {
    name: 'Argentina',
    code: '54',
    capital: 'Buenos Aires',
    iso2: 'AR',
  },
  {
    name: 'Armenia',
    code: '374',
    capital: 'Yerevan',
    iso2: 'AM',
  },
  {
    name: 'Aruba',
    code: '297',
    capital: 'Oranjestad',
    iso2: 'AW',
  },
  {
    name: 'Ascension',
    code: '247',
    capital: 'Georgetown, Ascension Island',
    iso2: 'AC',
  },
  {
    name: 'Australia',
    code: '61',
    capital: 'Canberra',
    iso2: 'AU',
  },
  {
    name: 'Austria',
    code: '43',
    capital: 'Vienna',
    iso2: 'AT',
  },
  {
    name: 'Azerbaijan',
    code: '994',
    capital: 'Baku',
    iso2: 'AZ',
  },
  {
    name: 'Bahamas',
    code: '1242',
    capital: 'Nassau',
    iso2: 'BS',
  },
  {
    name: 'Bahrain',
    code: '973',
    capital: 'Manama',
    iso2: 'BH',
  },
  {
    name: 'Bangladesh',
    code: '880',
    capital: 'Dhaka',
    iso2: 'BD',
  },
  {
    name: 'Barbados',
    code: '1246',
    capital: 'Bridgetown',
    iso2: 'BB',
  },
  {
    name: 'Caribbean',
    code: '1268',
    capital: 'Barbuda',
    iso2: 'AG',
  },
  {
    name: 'Belarus',
    code: '375',
    capital: 'Minsk',
    iso2: 'BY',
  },
  {
    name: 'Belgium',
    code: '32',
    capital: 'City of Brussels',
    iso2: 'BE',
  },
  {
    name: 'Belize',
    code: '501',
    capital: 'Belmopan',
    iso2: 'BZ',
  },
  {
    name: 'Benin',
    code: '229',
    capital: 'Porto-Novo',
    iso2: 'BJ',
  },
  {
    name: 'Bermuda',
    code: '1441',
    capital: 'Hamilton',
    iso2: 'BM',
  },
  {
    name: 'Bhutan',
    code: '975',
    capital: 'Thimphu',
    iso2: 'BT',
  },
  {
    name: 'Guinea-Bissau',
    code: '245',
    capital: 'Bissau',
    iso2: 'GW',
  },
  {
    name: 'Bolivia',
    code: '591',
    capital: 'Sucre',
    iso2: 'BO',
  },
  {
    name: 'Bosnia and Herzegovina',
    code: '387',
    capital: 'Sarajevo',
    iso2: 'BA',
  },
  {
    name: 'Botswana',
    code: '267',
    capital: 'Gaborone',
    iso2: 'BW',
  },
  {
    name: 'Brazil',
    code: '55',
    capital: 'Brasília',
    iso2: 'BR',
  },
  {
    name: 'British Indian Ocean Territory',
    code: '246',
    capital: 'Camp Justice',
    iso2: 'IO',
  },
  {
    name: 'British Virgin Islands',
    code: '1284',
    capital: 'Road Town',
    iso2: 'VG',
  },
  {
    name: 'Brunei Darussalam',
    code: '673',
    capital: 'Bandar Seri Begawan',
    iso2: 'BN',
  },
  {
    name: 'Bulgaria',
    code: '359',
    capital: 'Sofia',
    iso2: 'BG',
  },
  {
    name: 'Burkina Faso',
    code: '226',
    capital: 'Ouagadougou',
    iso2: 'BF',
  },
  {
    name: 'Burma',
    code: '95',
    capital: 'Naypyidaw',
    iso2: 'MM',
  },
  {
    name: 'Burundi',
    code: '257',
    capital: 'Bujumbura',
    iso2: 'BI',
  },
  {
    name: 'Cambodia',
    code: '855',
    capital: 'Phnom Penh',
    iso2: 'KH',
  },
  {
    name: 'Cameroon',
    code: '237',
    capital: 'Yaoundé',
    iso2: 'CM',
  },
  {
    name: 'US/Canada',
    code: '1',
    capital: 'Washington, DC',
    iso2: 'CA',
  },
  {
    name: 'United States',
    code: '1',
    capital: 'Washington, DC',
    iso2: 'US',
  },
  {
    name: 'Canada',
    code: '1',
    capital: 'Ottawa',
    iso2: 'CA',
  },
  {
    name: 'Cape Verde',
    code: '238',
    capital: 'Praia',
    iso2: 'CV',
  },
  {
    name: 'Caribbean Netherlands/Bonaire',
    code: '5997',
    capital: 'Kralendijk',
    iso2: 'BQ',
  },
  {
    name: 'Cayman Islands',
    code: '1345',
    capital: 'George Town',
    iso2: 'KY',
  },
  {
    name: 'Central African Republic',
    code: '236',
    capital: 'Bangui',
    iso2: 'CF',
  },
  {
    name: 'Chad',
    code: '235',
    capital: "N'Djamena",
    iso2: 'TD',
  },
  {
    name: 'New Zealand',
    code: '64',
    capital: 'Chatham Island',
    iso2: 'NZ',
  },
  {
    name: 'Chile',
    code: '56',
    capital: 'Santiago',
    iso2: 'CL',
  },
  {
    name: 'China',
    code: '86',
    capital: 'Beijing',
    iso2: 'CN',
  },
  {
    name: 'Christmas Island',
    code: '61',
    capital: 'Flying Fish Cove',
    iso2: 'CX',
  },
  {
    name: 'Cocos (Keeling) Islands',
    code: '61',
    capital: 'West Island, Cocos (Keeling) Islands',
    iso2: 'CC',
  },
  {
    name: 'Colombia',
    code: '57',
    capital: 'Bogotá',
    iso2: 'CO',
  },
  {
    name: 'Comoros',
    code: '269',
    capital: 'Moroni',
    iso2: 'KM',
  },
  {
    name: 'Republic of the Congo',
    code: '242',
    capital: 'Brazzaville',
    iso2: 'CG',
  },
  {
    name: 'Cook Islands',
    code: '682',
    capital: 'Avarua',
    iso2: 'CK',
  },
  {
    name: 'Costa Rica',
    code: '506',
    capital: 'San José',
    iso2: 'CR',
  },
  {
    name: "Côte d'Ivoire",
    code: '225',
    capital: 'Yamoussoukro',
    iso2: 'CI',
  },
  {
    name: 'Croatia',
    code: '385',
    capital: 'Zagreb',
    iso2: 'HR',
  },
  {
    name: 'Cuba',
    code: '53',
    capital: 'Havana',
    iso2: 'CU',
  },
  {
    name: 'Curaçao',
    code: '5999',
    capital: 'Willemstad',
    iso2: 'CW',
  },
  {
    name: 'Cyprus',
    code: '357',
    capital: 'Nicosia',
    iso2: 'CY',
  },
  {
    name: 'Czech Republic',
    code: '420',
    capital: 'Prague',
    iso2: 'CZ',
  },
  {
    name: 'Democratic Republic of the Congo',
    code: '243',
    capital: 'Kinshasa',
    iso2: 'CD',
  },
  {
    name: 'Denmark',
    code: '45',
    capital: 'Copenhagen',
    iso2: 'DK',
  },
  {
    name: 'British Indian Ocean Territory',
    code: '246',
    capital: 'Diego Garcia',
    iso2: 'IO',
  },
  {
    name: 'Djibouti',
    code: '253',
    capital: 'Djibouti',
    iso2: 'DJ',
  },
  {
    name: 'Dominica',
    code: '1767',
    capital: 'Roseau',
    iso2: 'DM',
  },
  {
    name: 'Dominican Republic',
    code: '1809',
    capital: 'Santo Domingo',
    iso2: 'DO',
  },
  {
    name: 'Dominican Republic',
    code: '1829',
    capital: 'Santo Domingo',
    iso2: 'DO',
  },
  {
    name: 'Dominican Republic',
    code: '1849',
    capital: 'Santo Domingo',
    iso2: 'DO',
  },
  {
    name: 'East Timor',
    code: '670',
    capital: 'Dili',
    iso2: 'TL',
  },
  {
    name: 'Ecuador',
    code: '593',
    capital: 'Quito',
    iso2: 'EC',
  },
  {
    name: 'Egypt',
    code: '20',
    capital: 'Cairo',
    iso2: 'EG',
  },
  {
    name: 'El Salvador',
    code: '503',
    capital: 'San Salvador',
    iso2: 'SV',
  },
  {
    name: 'Equatorial Guinea',
    code: '240',
    capital: 'Malabo',
    iso2: 'GQ',
  },
  {
    name: 'Eritrea',
    code: '291',
    capital: 'Asmara',
    iso2: 'ER',
  },
  {
    name: 'Estonia',
    code: '372',
    capital: 'Tallinn',
    iso2: 'EE',
  },
  {
    name: 'Ethiopia',
    code: '251',
    capital: 'Addis Ababa',
    iso2: 'ET',
  },
  {
    name: 'Falkland Islands',
    code: '500',
    capital: 'Stanley',
    iso2: 'FK',
  },
  {
    name: 'Faroe Islands',
    code: '298',
    capital: 'Tórshavn',
    iso2: 'FO',
  },
  {
    name: 'Federated States of Micronesia',
    code: '691',
    capital: 'Palikir',
    iso2: 'FM',
  },
  {
    name: 'Fiji',
    code: '679',
    capital: 'Suva',
    iso2: 'FJ',
  },
  {
    name: 'Finland',
    code: '358',
    capital: 'Helsinki',
    iso2: 'FI',
  },
  {
    name: 'France',
    code: '33',
    capital: 'Paris',
    iso2: 'FR',
  },
  {
    name: 'French Guiana',
    code: '594',
    capital: 'Cayenne',
    iso2: 'GF',
  },
  {
    name: 'French Polynesia',
    code: '689',
    capital: 'Papeete',
    iso2: 'PF',
  },
  {
    name: 'Gabon',
    code: '241',
    capital: 'Libreville',
    iso2: 'GA',
  },
  {
    name: 'Gambia',
    code: '220',
    capital: 'Banjul',
    iso2: 'GM',
  },
  {
    name: 'Georgia',
    code: '995',
    capital: 'Tbilisi',
    iso2: 'GE',
  },
  {
    name: 'Germany',
    code: '49',
    capital: 'Berlin',
    iso2: 'DE',
  },
  {
    name: 'Ghana',
    code: '233',
    capital: 'Accra',
    iso2: 'GH',
  },
  {
    name: 'Gibraltar',
    code: '350',
    capital: 'Gibraltar',
    iso2: 'GI',
  },
  {
    name: 'Greece',
    code: '30',
    capital: 'Athens',
    iso2: 'GR',
  },
  {
    name: 'Greenland',
    code: '299',
    capital: 'Nuuk',
    iso2: 'GL',
  },
  {
    name: 'Grenada',
    code: '1473',
    capital: "St. George's",
    iso2: 'GD',
  },
  {
    name: 'Guadeloupe',
    code: '590',
    capital: 'Basse-Terre',
    iso2: 'GP',
  },
  {
    name: 'Guam',
    code: '1671',
    capital: 'Hagåtña',
    iso2: 'GU',
  },
  {
    name: 'Cuba',
    code: '5399',
    capital: 'Guantanamo Bay Cuba',
    iso2: 'CU',
  },
  {
    name: 'Guatemala',
    code: '502',
    capital: 'Guatemala City',
    iso2: 'GT',
  },
  {
    name: 'Guinea',
    code: '224',
    capital: 'Conakry',
    iso2: 'GN',
  },
  {
    name: 'Guinea',
    code: '245',
    capital: 'Conakry',
    iso2: 'GN',
  },
  {
    name: 'Guyana',
    code: '592',
    capital: 'Georgetown',
    iso2: 'GY',
  },
  {
    name: 'Haiti',
    code: '509',
    capital: 'Port-au-Prince',
    iso2: 'HT',
  },
  {
    name: 'Honduras',
    code: '504',
    capital: 'Tegucigalpa',
    iso2: 'HN',
  },
  {
    name: 'Hong Kong',
    code: '852',
    capital: 'Hong Kong',
    iso2: 'HK',
  },
  {
    name: 'Hungary',
    code: '36',
    capital: 'Budapest',
    iso2: 'HU',
  },
  {
    name: 'Iceland',
    code: '354',
    capital: 'Reykjavik',
    iso2: 'IS',
  },
  {
    name: 'India',
    code: '91',
    capital: 'New Delhi',
    iso2: 'IN',
  },
  {
    name: 'Indonesia',
    code: '62',
    capital: 'Jakarta',
    iso2: 'ID',
  },
  {
    name: 'Iran',
    code: '98',
    capital: 'Tehran',
    iso2: 'IR',
  },
  {
    name: 'Iraq',
    code: '964',
    capital: 'Baghdad',
    iso2: 'IQ',
  },
  {
    name: 'Ireland',
    code: '353',
    capital: 'Dublin',
    iso2: 'IE',
  },
  {
    name: 'Israel',
    code: '972',
    capital: 'Jerusalem',
    iso2: 'IL',
  },
  {
    name: 'Italy',
    code: '39',
    capital: 'Rome',
    iso2: 'IT',
  },
  {
    name: 'Jamaica',
    code: '1876',
    capital: 'Kingston',
    iso2: 'JM',
  },
  {
    name: 'Jan Mayen/Svalbard',
    code: '4779',
    capital: 'Longyearbyen',
    iso2: 'SJ',
  },
  {
    name: 'Japan',
    code: '81',
    capital: 'Tokyo',
    iso2: 'JP',
  },
  {
    name: 'Jordan',
    code: '962',
    capital: 'Amman',
    iso2: 'JO',
  },
  {
    name: 'Kazakhstan',
    code: '76',
    capital: 'Astana',
    iso2: 'KZ',
  },
  {
    name: 'Kazakhstan',
    code: '77',
    capital: 'Astana',
    iso2: 'KZ',
  },
  {
    name: 'Kazakhstan',
    code: '997',
    capital: 'Astana',
    iso2: 'KZ',
  },
  {
    name: 'Kenya',
    code: '254',
    capital: 'Nairobi',
    iso2: 'KE',
  },
  {
    name: 'Kiribati',
    code: '686',
    capital: 'South Tarawa',
    iso2: 'KI',
  },
  {
    name: 'Kuwait',
    code: '965',
    capital: 'Kuwait City',
    iso2: 'KW',
  },
  {
    name: 'Kyrgyzstan',
    code: '996',
    capital: 'Bishkek',
    iso2: 'KG',
  },
  {
    name: 'Laos',
    code: '856',
    capital: 'Vientiane',
    iso2: 'LA',
  },
  {
    name: 'Latvia',
    code: '371',
    capital: 'Riga',
    iso2: 'LV',
  },
  {
    name: 'Lebanon',
    code: '961',
    capital: 'Beirut',
    iso2: 'LB',
  },
  {
    name: 'Lesotho',
    code: '266',
    capital: 'Maseru',
    iso2: 'LS',
  },
  {
    name: 'Liberia',
    code: '231',
    capital: 'Monrovia',
    iso2: 'LR',
  },
  {
    name: 'Libya',
    code: '218',
    capital: 'Tripoli',
    iso2: 'LY',
  },
  {
    name: 'Liechtenstein',
    code: '423',
    capital: 'Vaduz',
    iso2: 'LI',
  },
  {
    name: 'Lithuania',
    code: '370',
    capital: 'Vilnius',
    iso2: 'LT',
  },
  {
    name: 'Luxembourg',
    code: '352',
    capital: 'Luxembourg City',
    iso2: 'LU',
  },
  {
    name: 'China',
    code: '853',
    capital: 'Macau',
    iso2: 'MO',
  },
  {
    name: 'Macedonia',
    code: '389',
    capital: 'Skopje',
    iso2: 'MK',
  },
  {
    name: 'Madagascar',
    code: '261',
    capital: 'Antananarivo',
    iso2: 'MG',
  },
  {
    name: 'Malawi',
    code: '265',
    capital: 'Lilongwe',
    iso2: 'MW',
  },
  {
    name: 'Malaysia',
    code: '60',
    capital: 'Kuala Lumpur',
    iso2: 'MY',
  },
  {
    name: 'Maldives',
    code: '960',
    capital: 'Malé',
    iso2: 'MV',
  },
  {
    name: 'Mali',
    code: '223',
    capital: 'Bamako',
    iso2: 'ML',
  },
  {
    name: 'Malta',
    code: '356',
    capital: 'Valletta',
    iso2: 'MT',
  },
  {
    name: 'Marshall Islands',
    code: '692',
    capital: 'Majuro',
    iso2: 'MH',
  },
  {
    name: 'Martinique',
    code: '596',
    capital: 'Fort-de-France',
    iso2: 'MQ',
  },
  {
    name: 'Mauritania',
    code: '222',
    capital: 'Nouakchott',
    iso2: 'MR',
  },
  {
    name: 'Mauritius',
    code: '230',
    capital: 'Port Louis',
    iso2: 'MU',
  },
  {
    name: 'Mayotte',
    code: '262',
    capital: 'Mamoudzou',
    iso2: 'YT',
  },
  {
    name: 'Mexico',
    code: '52',
    capital: 'Mexico City',
    iso2: 'MX',
  },
  {
    name: 'USA',
    code: '1808',
    capital: 'Midway Island',

    iso2: '',
  },
  {
    name: 'Moldova',
    code: '373',
    capital: 'Chișinău',
    iso2: 'MD',
  },
  {
    name: 'Monaco',
    code: '377',
    capital: 'Monaco',
    iso2: 'MC',
  },
  {
    name: 'Mongolia',
    code: '976',
    capital: 'Ulaanbaatar',
    iso2: 'MN',
  },
  {
    name: 'Montenegro',
    code: '382',
    capital: 'Podgorica',
    iso2: 'ME',
  },
  {
    name: 'Montserrat',
    code: '1664',
    capital: 'Plymouth',
    iso2: 'MS',
  },
  {
    name: 'Morocco',
    code: '212',
    capital: 'Rabat',
    iso2: 'MA',
  },
  {
    name: 'Mozambique',
    code: '258',
    capital: 'Maputo',
    iso2: 'MZ',
  },
  {
    name: 'N. Korea',
    code: '850',
    capital: 'Pyongyang',
    iso2: 'KP',
  },
  {
    name: 'Namibia',
    code: '264',
    capital: 'Windhoek',
    iso2: 'NA',
  },
  {
    name: 'Nauru',
    code: '674',
    capital: 'Yaren',
    iso2: 'NR',
  },
  {
    name: 'Nepal',
    code: '977',
    capital: 'Kathmandu',
    iso2: 'NP',
  },
  {
    name: 'Netherlands',
    code: '31',
    capital: 'Amsterdam',
    iso2: 'NL',
  },
  {
    name: 'Nevis',
    code: '1869',
    capital: 'Charlestown',
    iso2: 'KN',
  },
  {
    name: 'New Caledonia',
    code: '687',
    capital: 'Nouméa',
    iso2: 'NC',
  },
  {
    name: 'New Zealand',
    code: '64',
    capital: 'Wellington',
    iso2: 'NZ',
  },
  {
    name: 'Nicaragua',
    code: '505',
    capital: 'Managua',
    iso2: 'NI',
  },
  {
    name: 'Niger',
    code: '227',
    capital: 'Niamey',
    iso2: 'NE',
  },
  {
    name: 'Nigeria',
    code: '234',
    capital: 'Abuja',
    iso2: 'NG',
  },
  {
    name: 'Niue',
    code: '683',
    capital: 'Alofi',
    iso2: 'NU',
  },
  {
    name: 'Norfolk Island',
    code: '672',
    capital: 'Kingston',
    iso2: 'NF',
  },
  {
    name: 'Northern Mariana Islands',
    code: '1670',
    capital: 'Capitol Hill, Saipan',
    iso2: 'MP',
  },
  {
    name: 'Norway',
    code: '47',
    capital: 'Oslo',
    iso2: 'NO',
  },
  {
    name: 'Oman',
    code: '968',
    capital: 'Muscat',
    iso2: 'OM',
  },
  {
    name: 'Pakistan',
    code: '92',
    capital: 'Islamabad',
    iso2: 'PK',
  },
  {
    name: 'Palau',
    code: '680',
    capital: 'Ngerulmud',
    iso2: 'PW',
  },
  {
    name: 'Panama',
    code: '507',
    capital: 'Panama City',
    iso2: 'PA',
  },
  {
    name: 'Papua New Guinea',
    code: '675',
    capital: 'Port Moresby',
    iso2: 'PG',
  },
  {
    name: 'Paraguay',
    code: '595',
    capital: 'Asunción',
    iso2: 'PY',
  },
  {
    name: 'Peru',
    code: '51',
    capital: 'Lima',
    iso2: 'PE',
  },
  {
    name: 'Philippines',
    code: '63',
    capital: 'Manila',
    iso2: 'PH',
  },
  {
    name: 'Pitcairn Islands',
    code: '64',
    capital: 'Adamstown',
    iso2: 'PN',
  },
  {
    name: 'Poland',
    code: '48',
    capital: 'Warsaw',
    iso2: 'PL',
  },
  {
    name: 'Portugal',
    code: '351',
    capital: 'Lisbon',
    iso2: 'PT',
  },
  {
    name: 'Puerto Rico',
    code: '1787',
    capital: 'San Juan',
    iso2: 'PR',
  },
  {
    name: 'Puerto Rico',
    code: '1939',
    capital: 'San Juan',
    iso2: 'PR',
  },
  {
    name: 'Qatar',
    code: '974',
    capital: 'Doha',
    iso2: 'QA',
  },
  {
    name: 'Réunion',
    code: '262',
    capital: 'Saint-Denis',
    iso2: 'RE',
  },
  {
    name: 'Romania',
    code: '40',
    capital: 'Bucharest',
    iso2: 'RO',
  },
  {
    name: 'Russia',
    code: '7',
    capital: 'Moscow',
    iso2: 'RU',
  },
  {
    name: 'Rwanda',
    code: '250',
    capital: 'Kigali',
    iso2: 'RW',
  },
  {
    name: 'S. Georgia & the S. Sandwich Islands',
    code: '500',
    capital: 'King Edward Point',
    iso2: 'GS',
  },
  {
    name: 'S. Korea',
    code: '82',
    capital: 'Seoul',
    iso2: 'KR',
  },
  {
    name: 'Georgia',
    code: '99534',
    capital: 'S. Ossetia',
    iso2: 'GE',
  },
  {
    name: 'Saint Barthélemy',
    code: '590',
    capital: 'Gustavia',
    iso2: 'BL',
  },
  {
    name: 'Saint Helena',
    code: '290',
    capital: 'Jamestown',
    iso2: 'SH',
  },
  {
    name: 'Saint Kitts and Nevis',
    code: '1869',
    capital: 'Basseterre',
    iso2: 'KN',
  },
  {
    name: 'Saint Lucia',
    code: '1758',
    capital: 'Castries',
    iso2: 'LC',
  },
  {
    name: 'Saint Martin (France)',
    code: '590',
    capital: 'Marigot',
    iso2: 'MF',
  },
  {
    name: 'Saint Pierre and Miquelon',
    code: '508',
    capital: 'Saint-Pierre',
    iso2: 'PM',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    code: '1784',
    capital: 'Kingstown',
    iso2: 'VC',
  },
  {
    name: 'Samoa',
    code: '685',
    capital: 'Apia',
    iso2: 'WS',
  },
  {
    name: 'San Marino',
    code: '378',
    capital: 'San Marino',
    iso2: 'SM',
  },
  {
    name: 'São Tomé and Príncipe',
    code: '239',
    capital: 'São Tomé',
    iso2: 'ST',
  },
  {
    name: 'Saudi Arabia',
    code: '966',
    capital: 'Riyadh',
    iso2: 'SA',
  },
  {
    name: 'Senegal',
    code: '221',
    capital: 'Dakar',
    iso2: 'SN',
  },
  {
    name: 'Serbia',
    code: '381',
    capital: 'Belgrade',
    iso2: 'RS',
  },
  {
    name: 'Seychelles',
    code: '248',
    capital: 'Victoria',
    iso2: 'SC',
  },
  {
    name: 'Sierra Leone',
    code: '232',
    capital: 'Freetown',
    iso2: 'SL',
  },
  {
    name: 'Singapore',
    code: '65',
    capital: 'Singapore',
    iso2: 'SG',
  },
  {
    name: 'Sint Eustatius',
    code: '5993',
    capital: 'Oranjestad',
    iso2: 'BQ',
  },
  {
    name: 'Sint Maarten (Netherlands)',
    code: '1721',
    capital: 'Philipsburg',
    iso2: 'SX',
  },
  {
    name: 'Slovakia',
    code: '421',
    capital: 'Bratislava',
    iso2: 'SK',
  },
  {
    name: 'Slovenia',
    code: '386',
    capital: 'Ljubljana',
    iso2: 'SI',
  },
  {
    name: 'Solomon Islands',
    code: '677',
    capital: 'Honiara',
    iso2: 'SB',
  },
  {
    name: 'Somalia',
    code: '252',
    capital: 'Mogadishu',
    iso2: 'SO',
  },
  {
    name: 'South Africa',
    code: '27',
    capital: 'Cape Town',
    iso2: 'ZA',
  },
  {
    name: 'South Sudan',
    code: '211',
    capital: 'Juba',
    iso2: 'SS',
  },
  {
    name: 'Spain',
    code: '34',
    capital: 'Madrid',
    iso2: 'ES',
  },
  {
    name: 'Sri Lanka',
    code: '94',
    capital: 'Sri Jayawardenepura Kotte',
    iso2: 'LK',
  },
  {
    name: 'St. of Palestine',
    code: '970',
    capital: 'East Jerusalem',
    iso2: 'PS',
  },
  {
    name: 'Sudan',
    code: '249',
    capital: 'Khartoum',
    iso2: 'SD',
  },
  {
    name: 'Suriname',
    code: '597',
    capital: 'Paramaribo',
    iso2: 'SR',
  },
  {
    name: 'Eswatini',
    code: '268',
    capital: 'Mbabane',
    iso2: 'SZ',
  },
  {
    name: 'Sweden',
    code: '46',
    capital: 'Stockholm',
    iso2: 'SE',
  },
  {
    name: 'Switzerland',
    code: '41',
    capital: 'Bern',
    iso2: 'CH',
  },
  {
    name: 'Syria',
    code: '963',
    capital: 'Damascus',
    iso2: 'SY',
  },
  {
    name: 'Taiwan',
    code: '886',
    capital: 'Taipei',
    iso2: 'TW',
  },
  {
    name: 'Tajikistan',
    code: '992',
    capital: 'Dushanbe',
    iso2: 'TJ',
  },
  {
    name: 'Tanzania',
    code: '255',
    capital: 'Dodoma',
    iso2: 'TZ',
  },
  {
    name: 'Thailand',
    code: '66',
    capital: 'Bangkok',
    iso2: 'TH',
  },
  {
    name: 'Togo',
    code: '228',
    capital: 'Lomé',
    iso2: 'TG',
  },
  {
    name: 'Tokelau',
    code: '690',
    capital: 'Fakaofo',
    iso2: 'TK',
  },
  {
    name: 'Tonga',
    code: '676',
    capital: "Nukuʻalofa",
    iso2: 'TO',
  },
  {
    name: 'Trinidad and Tobago',
    code: '1868',
    capital: 'Port of Spain',
    iso2: 'TT',
  },
  {
    name: 'Tristan da Cunha',
    code: '2908',
    capital: 'Edinburgh of the Seven Seas',
    iso2: 'SH',
  },
  {
    name: 'Tunisia',
    code: '216',
    capital: 'Tunis',
    iso2: 'TN',
  },
  {
    name: 'Türkiye',
    code: '90',
    capital: 'Ankara',
    iso2: 'TR',
  },
  {
    name: 'Turkmenistan',
    code: '993',
    capital: 'Ashgabat',
    iso2: 'TM',
  },
  {
    name: 'Turks and Caicos Islands',
    code: '1649',
    capital: 'Cockburn Town',
    iso2: 'TC',
  },
  {
    name: 'Tuvalu',
    code: '688',
    capital: 'Funafuti',
    iso2: 'TV',
  },
  {
    name: 'Uganda',
    code: '256',
    capital: 'Kampala',
    iso2: 'UG',
  },
  {
    name: 'Ukraine',
    code: '380',
    capital: 'Kiev',
    iso2: 'UA',
  },
  {
    name: 'United Arab Emirates',
    code: '971',
    capital: 'Abu Dhabi',
    iso2: 'AE',
  },
  {
    name: 'United Kingdom/Guernsey/Jersey',
    code: '44',
    capital: 'London',
    iso2: 'GB',
  },
  {
    name: 'Uruguay',
    code: '598',
    capital: 'Montevideo',
    iso2: 'UY',
  },
  {
    name: 'US Virgin Islands',
    code: '1340',
    capital: 'Charlotte Amalie',
    iso2: 'VI',
  },
  {
    name: 'Uzbekistan',
    code: '998',
    capital: 'Tashkent',
    iso2: 'UZ',
  },
  {
    name: 'Vanuatu',
    code: '678',
    capital: 'Port Vila',
    iso2: 'VU',
  },
  {
    name: 'Vatican City State',
    code: '379',
    capital: 'Vatican City',
    iso2: 'VA',
  },
  {
    name: 'Venezuela',
    code: '58',
    capital: 'Caracas',
    iso2: 'VE',
  },
  {
    name: 'Vietnam',
    code: '84',
    capital: 'Hanoi',
    iso2: 'VN',
  },
  {
    name: 'USA',
    code: '1808',
    capital: 'Wake Island',
    iso2: 'UM',
  },
  {
    name: 'Wallis and Futuna',
    code: '681',
    capital: 'Mata Utu',
    iso2: 'WF',
  },
  {
    name: 'Yemen',
    code: '967',
    capital: "Sana'a",
    iso2: 'YE',
  },
  {
    name: 'Zambia',
    code: '260',
    capital: 'Lusaka',
    iso2: 'ZM',
  },
  {
    name: 'Tanzania',
    code: '255',
    capital: 'Zanzibar City',
    iso2: 'TZ',
  },
  {
    name: 'Zimbabwe',
    code: '263',
    capital: 'Harare',
    iso2: 'ZW',
  },
  {
    name: 'Kosovo',
    code: '383',
    capital: 'Pristina',
    iso2: 'XK',
  },
  {
    name: 'Toll-free telephone number',
    code: '800',
    capital: '',
    iso2: 'XT',
  },
  {
    name: 'Shared-cost service',
    code: '808',
    capital: '',
    iso2: 'XS',
  },
  {
    name: 'Inmarsat',
    code: '870',
    capital: '',
    iso2: 'XN',
  },
  {
    name: 'Universal Personal Telecommunications',
    code: '878',
    capital: '',
    iso2: 'XP',
  },
  {
    name: 'Global Mobile Satellite System',
    code: '881',
    capital: '',
    iso2: 'XG', // Has "areas"
  },
  {
    name: 'International Networks',
    code: '882',
    capital: '',
    iso2: 'XV', // Has many "areas"
  },
  {
    name: 'International Networks',
    code: '883',
    capital: '',
    iso2: 'XV', // Has many "areas"
  },
  {
    name: 'International Premium Rate Service',
    code: '979',
    capital: '',
    iso2: 'XR', // Has "areas"
  },
  {
    name: 'International Telecommunications Public Correspondence Service',
    code: '991',
    capital: '',
    iso2: 'XC',
  },
];
